version: '2'

services:
  orderer.idtree.com:
    container_name: orderer.idtree.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/idtree.com/orderers/orderer.idtree.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/idtree.com/orderers/orderer.idtree.com/tls/:/var/hyperledger/orderer/tls
      - orderer.idtree.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.superadmin.idtree.com:
    container_name: peer0.superadmin.idtree.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.superadmin.idtree.com
      - CORE_PEER_ADDRESS=peer0.superadmin.idtree.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.superadmin.idtree.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.superadmin.idtree.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.superadmin.idtree.com:7051
      - CORE_PEER_LOCALMSPID=superadminMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/superadmin.idtree.com/peers/peer0.superadmin.idtree.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/superadmin.idtree.com/peers/peer0.superadmin.idtree.com/tls:/etc/hyperledger/fabric/tls
      - peer0.superadmin.idtree.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.superadmin.idtree.com:
    container_name: peer1.superadmin.idtree.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.superadmin.idtree.com
      - CORE_PEER_ADDRESS=peer1.superadmin.idtree.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.superadmin.idtree.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.superadmin.idtree.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.superadmin.idtree.com:7051
      - CORE_PEER_LOCALMSPID=superadminMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/superadmin.idtree.com/peers/peer1.superadmin.idtree.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/superadmin.idtree.com/peers/peer1.superadmin.idtree.com/tls:/etc/hyperledger/fabric/tls
      - peer1.superadmin.idtree.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.users.idtree.com:
    container_name: peer0.users.idtree.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.users.idtree.com
      - CORE_PEER_ADDRESS=peer0.users.idtree.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.users.idtree.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.users.idtree.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.users.idtree.com:10051
      - CORE_PEER_LOCALMSPID=usersMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/users.idtree.com/peers/peer0.users.idtree.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/users.idtree.com/peers/peer0.users.idtree.com/tls:/etc/hyperledger/fabric/tls
      - peer0.users.idtree.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.users.idtree.com:
    container_name: peer1.users.idtree.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.users.idtree.com
      - CORE_PEER_ADDRESS=peer1.users.idtree.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.users.idtree.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.users.idtree.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.users.idtree.com:9051
      - CORE_PEER_LOCALMSPID=usersMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/users.idtree.com/peers/peer1.users.idtree.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/users.idtree.com/peers/peer1.users.idtree.com/tls:/etc/hyperledger/fabric/tls
      - peer1.users.idtree.com:/var/hyperledger/production
    ports:
      - 10051:10051
